- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement # DeltaV - JobSecurityOfficer time requirement. Make them experienced in proper officer work.
      role: JobSecurityOfficer
      time: 14400 # 4 hrs
    - !type:RoleTimeRequirement # DeltaV - JobDetective time requirement. Give them an understanding of basic forensics.
      role: JobDetective
      time: 7200 # 2 hrs
    - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all security roles
  whitelisted: true # Echo Station: Require explicit role whitelisting
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Armory
  - Maintenance
  #- Service # Delta V: Access adjustments
  - External
  - Detective
  - Corpsman # DeltaV - corpsman access.
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity # DeltaV
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58Nonlethal
