- type: job
  id: ExecutiveOfficer
  name: job-name-executive-officer
  description: job-description-executive-officer
  playTimeTracker: JobExecutiveOfficer
  setPreference: false # Not shown in lobby
  overrideConsoleVisibility: true # but it IS shown in the ID card computer
  icon: "JobIconExecutiveOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access: # Copies from the "AllAccess" access group, and modified
  - EmergencyShuttleRepealAll
  #- Captain # This is the ONLY exception currently.
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Command
  - Cryogenics
  - Security
  - Detective
  - Armory
  #- Brig #Delta V Removed
  - Lawyer
  - Engineering
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - Service
  - Maintenance
  - External
  - Janitor
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Mail # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  - Paramedic # DeltaV - Add Paramedic access
  - Psychologist # DeltaV - Add Psychologist access
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
  - Justice # DeltaV - Add Justice dept access
  - ChiefJustice # DeltaV - Add Chief Justice access
  - Prosecutor # DeltaV - Add Prosecutor access
  - Clerk # DeltaV - Add Clerk access
  - Corpsman # DeltaV - Add Corpsman access
