[game]
hostname = "[EN][MRP/HRP] 🔷 Echo Station: Alpha | Public tryout slots! [US East]"

# Role timers are now ON, but all time requirements are multiplied by the multiplier below.
role_timers = true
role_timers_multiplier = 0.2 # Increment this over time as people get more playtime in
role_whitelist = true

[hub]
# Don't appear in public listings just yet.
advertise = true
# English, America > North America > East, Medium RP, don't guess tags based on server name.
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"

# Individual instance configs should set the following settings:
#
# [discord]
# ahelp_webhook = your-webhook-url-here
# ahelp_footer_icon = url-to-footer-icon-here https://discord.com/developers/docs/resources/channel#embed-object-embed-footer-structure
# ahelp_avatar =
#
# [database]
# engine = "postgres"
# pg_host = "...
# pg_port = 5432
# pg_database = ss14
# pg_user = "...
# pg_password = "..."
