- type: job
  id: Prosecutor
  name: job-name-prosecutor
  description: job-description-prosecutor
  playTimeTracker: JobProsecutor
  requirements:
#  - !type:OverallPlaytimeRequirement # Echo: No overall requirement (10hr sec == 10hr overall)
#    time: 36000 # 10 hrs
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 36000 # 6 hours # Echo: 10 hrs
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Security roles
  startingGear: ProsecutorGear
  icon: "JobIconProsecutor"
  supervisors: job-supervisors-hos # Echo: No Justice
  canBeAntag: false
  access:
  - Prosecutor
  - Security # Echo: No justice
  - Maintenance
  special: # Echo: Since Prosecutor is now Security, they get a mindshield
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ProsecutorGear
  equipment:
    #jumpsuit: ClothingUniformJumpsuitProsecutor
    #neck: ClothingNeckProsecutorbadge
    #back: ClothingBackpackLawyerFilled
    shoes: ClothingShoesBootsLaceup
    id: ProsecutorPDA
    ears: ClothingHeadsetSecurity # Echo: No justice
    # TODO add copy of space law
  inhand:
  - BriefcaseBrownFilled
  #innerClothingSkirt: ClothingUniformJumpskirtProsecutor
  #satchel: ClothingBackpackSatchelFilled
  #duffelbag: ClothingBackpackDuffelFilled


