- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  antagAdvantage: 4 # DeltaV - Reduced TC: Security Radio and Access
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
      department: Security
      time: 14400 # 4 hours
    - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Justice roles
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-hop  # Delta V - Change supervisor to chief justice # Echo: No Justice department
  access:
  - Service #- DeltaV, removed from service department # Echo: No Justice department
  #- Justice # DeltaV - Justice dept # Echo: No Justice department
  - Lawyer
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetService # DeltaV - Added lawyer to justice department # Echo: No Justice department
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw
